---
title: "basic model simulation"
author: "anjie & gal"
date: "1/12/2022"
output: html_document
---

```{r}
library(tidyverse)
library(here)
library(matrixStats)
library(partitions)
library(tictoc)
library(LaplacesDemon)
library(Brobdingnag)

source(here("helper/make_scheme_and_params.R"))
source(here("helper/initialization.R"))

```


```{r}
alpha_prior = c(1)
beta_prior = c(3, 5, 10, 30)

model_params <- expand_grid(alpha_prior, beta_prior) %>% 
    mutate(params_info = paste("ap", alpha_prior, 
                               "bp", beta_prior, 
                               sep = "_"),
           params_id = row_number())


# set stimuli-related parameters 
features_df <- tibble(
  n_features = c(6, 6), 
  on_features_n = c(1, 3)
)
sequence_scheme = c("BBBBBD", "BDBBBB", "BBBDBB","BBBBBB")

stims_df <- set_stim_params(sequence_scheme, features_df)


full_params_df <- make_simulation_params(n_sim = 1,
                                        model_params, 
                                        stims_df)

```


```{r}
 get_surprise <- function(alpha_count, beta_count, observation){
   p <- alpha_count / (alpha_count + beta_count)
   return (if_else(observation, -log2(p), -log2(1-p)))
 }


get_kl <- function(old_alpha_count, old_beta_count, 
                   curr_alpha_count, curr_beta_count){
  
  dbeta_grid <- seq(0.0001, 1, 0.0001)
  
  prior <- dbeta(dbeta_grid, old_alpha_count, old_beta_count) / sum(dbeta(dbeta_grid, 
                                                                             old_alpha_count, 
                                                                             old_beta_count))
  
  post <- dbeta(dbeta_grid, curr_alpha_count, curr_beta_count) / sum(dbeta(dbeta_grid, 
                                                                          curr_alpha_count, 
                                                                          curr_beta_count))
  
  return(philentropy::KL(rbind( post, prior), unit = "log"))

  
}
```


```{r}
run_basic_model <- function(params){
  # initialize the model that keeps track of all the IM 
  total_trial_number <- max((params$stimuli_sequence$data[[1]])$trial_number)
  
  model <- tibble(
   # params_info = rep(params$params_info, total_trial_number),
    trial_number = seq(1, total_trial_number),  
    kl = rep(NA_real_, total_trial_number), 
    surprisal = rep(NA_real_, total_trial_number)
  )
  
  # initialize two matrices that keep track of the alpha count and beta count 
  alphas <- matrix(data = NA, nrow = total_trial_number + 1, # plus one because first row recording priors  
                   ncol = params$n_features)
  
  betas <- matrix(data = NA, nrow = total_trial_number + 1,  # plus one because first row recording priors  
                   ncol = params$n_features)
  
  # set up the priors 
  alphas[1, ] <- params$alpha_prior
  betas[1, ] <- params$beta_prior
  
  # initialize two vectors that keeps track of the feature-based suprirsal and KL 
  feature_surprisal <- matrix(data = NA, nrow = 1, 
                   ncol = params$n_features)
  
  feature_kl <- matrix(data = NA, nrow = 1, 
                   ncol = params$n_features)
  
  # iterate through the sequence 
  for (trial_number in 1:total_trial_number){
    # iterate through all features after observing the trial  
    for (f in 1:params$n_features){
      # update the two matrices 
      if (pull(params$stimuli_sequence$data[[1]][trial_number, f]) == TRUE){
        # when true, accumulating alpha count, retaining beta count 
        alphas[trial_number+1, f] <- alphas[trial_number, f] + 1
        betas[trial_number+1, f] <- betas[trial_number, f]
      }else{
        # when false, accumulating beta count 
        alphas[trial_number+1, f] <- alphas[trial_number, f]
        betas[trial_number+1, f] <- betas[trial_number, f] + 1
      }
      
      # update the S and KL matrices 
      #
      feature_surprisal[1,f] <- get_surprise(alphas[trial_number+1, f], 
                                             betas[trial_number+1, f], 
                                             pull(params$stimuli_sequence$data[[1]][trial_number, f]))
      
      feature_kl[1, f] <- get_kl(alphas[trial_number, f], betas[trial_number, f], 
                                 alphas[trial_number+1, f], betas[trial_number+1, f])
      
    
    }
    # sum across the s and kl 
    trial_surprisal <- sum(feature_surprisal)
    trial_kl <- sum(feature_kl)
    # update the model for values 
    model$kl[trial_number] <- trial_kl 
    model$surprisal[trial_number] <- trial_surprisal
    
  } #for loop for updating 
  
  return (model)
  
}
```


```{r}
all_sims_res <- full_params_df %>%
  mutate(row_number = row_number()) %>% 
  group_by(row_number) %>% 
  nest() %>%
  mutate(results = map(data,
                       function(df) run_basic_model(params = df))) %>%
 unnest(cols = c(data, results))
```



```{r}
all_sims_res %>% 
  pivot_longer(cols = c("surprisal", "kl"), 
               names_to = "Information theoretic measurement", 
               values_to = "i_val") %>%
  filter(params_info == "ap_1_bp_3") %>% 
  group_by(row_number, params_info, n_features, on_features_n, sequence_scheme) %>% 
  ggplot(aes(x = trial_number, y = i_val, color = as.factor(on_features_n))) + 
  geom_point()+ 
  geom_line() + 
  facet_grid(`Information theoretic measurement`~sequence_scheme, scales = "free")
```

# some preliminary preprocessing 

```{r}
tidy_all_sim_res <- all_sims_res %>% 
  rowwise() %>% 
  mutate(
   complexity = case_when(
        grepl("nf_6_of_1",stim_info) ~ "simple", 
        grepl("nf_6_of_3", stim_info) ~ "complex"
      ), 
      sequence_scheme_print = case_when(
        sequence_scheme == "BBBBBB" ~ "No Deviant", 
        sequence_scheme == "BDBBBB" ~ "Deviant at 2nd Trial", 
        sequence_scheme == "BBBDBB" ~ "Deviant at 4th Trial", 
        sequence_scheme == "BBBBBD" ~ "Deviant at Last Trial")
)
                
  
  
  
 
```


# see correlation with the behavioral data 

```{r}
b_res <- read_csv(here("data/processed_rt_task_data.csv"))

b_res_print <- b_res %>% 
  mutate(sequence_scheme = case_when(
    deviant_position == 2 ~ "BDBBBB", 
    deviant_position == 4 ~ "BBBDBB", 
    deviant_position == 6 ~ "BBBBBD", 
    TRUE ~ "BBBBBB", 
  ), 
  sequence_scheme_print = case_when(
    sequence_scheme == "BBBBBB" ~ "No Deviant", 
    sequence_scheme == "BDBBBB" ~ "Deviant at 2nd Trial", 
    sequence_scheme == "BBBDBB" ~ "Deviant at 4th Trial", 
    sequence_scheme == "BBBBBD" ~ "Deviant at Last Trial"
  ), 
  log_trial_looking_time = log(trial_looking_time)) %>% 
  separate(block_type, into = c("complexity", "similarity"), sep = "_") %>% 
  select(subject, complexity, trial_number, 
         sequence_scheme, sequence_scheme_print, trial_looking_time, log_trial_looking_time)

# calculate smean.cl.b


b_res_summary <- b_res_print %>% 
  group_by(trial_number, sequence_scheme, sequence_scheme_print, complexity) %>%
  summarise(
    trial_looking_time = mean(trial_looking_time), 
    log_trial_looking_time = mean(log_trial_looking_time)
  ) 


b_res_summary

```

```{r}
basic_sim_behavior <- tidy_all_sim_res %>% 
  ungroup() %>% 
  left_join(b_res_summary, by = c("sequence_scheme", "trial_number", "sequence_scheme_print", "complexity"))

d <- basic_sim_behavior %>% 
  nest_by(params_info)


d$kl_r <- unlist(map(d$data, function(x){
    r <- cor(x$trial_looking_time, x$kl, method = "pearson")
  }))
 
d$kl_r_log <- unlist(map(d$data, function(x){
    r <- cor(x$log_trial_looking_time, log(x$kl), method = "pearson")
}))


d$surprisal_r <- unlist(map(d$data, function(x){
    r <- cor(x$trial_looking_time, x$surprisal, method = "pearson")
  }))
 
d$surprisal_r_log <- unlist(map(d$data, function(x){
    r <- cor(x$log_trial_looking_time, log(x$surprisal), method = "pearson")
}))

d
  
```




