---
title: "RANCH Comparison"
author: "anjie"
date: "8/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(matrixStats)
library(partitions)
library(tictoc)
library(LaplacesDemon)
library(Brobdingnag)

source(here("helper/make_scheme_and_params.R"))
source(here("helper/initialization.R"))
source(here("helper/probability_computations.R"))
source(here("helper/main_simulation_helper.R"))


# set up multicore sims
#future::plan(multicore)
```

Figuring out the sequence and generate the stimuli sequence with all the parameters 

# RANCH 

## EIG 

```{r}

# set model-related parameters 
alpha_epsilons = c(1)
beta_epsilons = c(4)
alpha_priors = c(1)
beta_priors = c(10)
noise_parameters = c(0.065)
world_EIGs = c(0.01)
forced_exposure_n = c(30)
max_observation = 2000

model_params <- set_model_params(alpha_priors, beta_priors, 
                alpha_epsilons, beta_epsilons, 
                noise_parameters, world_EIGs, max_observation, forced_exposure_n)


# set stimuli-related parameters 
features_df <- tibble(
  n_features = c(1), 
  on_features_n = c(1)
)
sequence_scheme = c("BBBBBB")

#stims_df_block <- set_stim_params_by_block(sequence_scheme, features_df)

stims_df <- set_stim_params(sequence_scheme, features_df)


full_params_df <- make_simulation_params(n_sim = 20,
                                        model_params, 
                                        stims_df)
```


```{r}
tic()
all_sims_res <- full_params_df %>%
  mutate(row_number = row_number()) %>% 
  group_by(row_number) %>% 
  nest() %>%
  mutate(results = map(data,
                       function(df) main_simulation(params = df))) %>%
  unnest(cols = c(data, results))
toc()
```




Clean and visualize. 

```{r}
all_sims_res %>% 
  group_by(row_number, params_id, n_features, sequence_scheme, stimulus_idx) %>% 
  filter(!is.na(stimulus_idx)) %>% 
  summarise(sample_n = n()) %>% 
  ggplot(aes(x = stimulus_idx, y = sample_n)) + 
  stat_summary(position = position_dodge(width = .1),fun.data = "mean_cl_boot") + 
  facet_wrap(~sequence_scheme)

```


```{r}
all_sims_res %>% 
  group_by(row_number, params_id, n_features, on_features_n, sequence_scheme, stimulus_idx) %>% 
  filter(!is.na(stimulus_idx)) %>% 
  summarise(sample_n = n()) %>% 
  ggplot(aes(x = stimulus_idx, y = sample_n, group = as.factor(on_features_n))) + 
  stat_summary(aes(color = as.factor(on_features_n)), position =position_dodge(width = .1),  fun.data = "mean_cl_boot") + 
  facet_wrap(~sequence_scheme)


  #geom_line(alpha = .1, aes(color = n_features)) + 
```


## Surprisal 

```{r}

model_params$measurement <- "surprisal"


full_params_df <- make_simulation_params(n_sim = 1,
                                        model_params, 
                                        stims_df)
```


```{r}
tic()
all_sims_res <- full_params_df %>%
  mutate(row_number = row_number()) %>% 
  group_by(row_number) %>% 
  nest() %>%
  mutate(results = map(data,
                       function(df) backward_IM_main_simulation(params = df))) %>%
  unnest(cols = c(data, results))
toc()

```

```{r}
all_sims_res %>% 
  group_by(row_number, params_id, n_features, on_features_n, sequence_scheme, stimulus_idx) %>% 
  filter(!is.na(stimulus_idx)) %>% 
  summarise(sample_n = n()) %>% 
  ggplot(aes(x = stimulus_idx, y = sample_n, group = as.factor(on_features_n))) + 
  stat_summary(aes(color = as.factor(on_features_n)), position =position_dodge(width = .1),  fun.data = "mean_cl_boot") + 
  facet_wrap(~sequence_scheme)

```


## KL 

```{r}
model_params$measurement <- "KL"
full_params_df <- make_simulation_params(n_sim = 1,
                                        model_params, 
                                        stims_df)

```

```{r}
tic()
all_sims_res <- full_params_df %>%
  mutate(row_number = row_number()) %>% 
  group_by(row_number) %>% 
  nest() %>%
  mutate(results = map(data,
                       function(df) backward_IM_main_simulation(params = df))) %>%
  unnest(cols = c(data, results))
toc()
```

```{r}
all_sims_res %>% 
  group_by(row_number, params_id, n_features, on_features_n, sequence_scheme, stimulus_idx) %>% 
  filter(!is.na(stimulus_idx)) %>% 
  summarise(sample_n = n()) %>% 
  ggplot(aes(x = stimulus_idx, y = sample_n, group = as.factor(on_features_n))) + 
  stat_summary(aes(color = as.factor(on_features_n)), position =position_dodge(width = .1),  fun.data = "mean_cl_boot") + 
  facet_wrap(~sequence_scheme)
```

# BASELINE

## No noise
To implement no noise, set epsilon = 0, change the grid_epsilon = c(0.000001) (for numerical stability)

## Random 

```{r}
all_sims_res <- full_params_df %>%
  mutate(row_number = row_number()) %>% 
  group_by(row_number) %>% 
  nest() %>%
  mutate(results = map(data,
                       function(df) main_simulation_random_looking(params = df))) %>%
  unnest(cols = c(data, results))

all_sims_res %>% 
  group_by(row_number, params_id, n_features, on_features_n, sequence_scheme, stimulus_idx) %>% 
  filter(!is.na(stimulus_idx)) %>% 
  summarise(sample_n = n()) %>% 
  ggplot(aes(x = stimulus_idx, y = sample_n, group = as.factor(on_features_n))) + 
  stat_summary(aes(color = as.factor(on_features_n)), position =position_dodge(width = .1),  fun.data = "mean_cl_boot") + 
  facet_wrap(~sequence_scheme)
```



