---
title: "Model behaviors investigation"
author: "anjie"
date: "11/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(matrixStats)
library(partitions)
library(tictoc)
library(LaplacesDemon)
library(patchwork)


source(here("helper/make_scheme_and_params.R"))
source(here("helper/initialization.R"))
source(here("helper/probability_computations.R"))
source(here("misc/model_diagnosis/main_simulation_with_visualization.R"))


```


# Understanding dishabituation patterns 

```{r}
alpha_epsilons = c(1)
beta_epsilons = c(10)
alpha_priors = c(1,10,30)
beta_priors = c(1,10,30)
noise_parameters = c(0)
world_EIGs = c(0.001)
max_observation = c(800)

model_params <- set_model_params(alpha_priors, beta_priors, 
                alpha_epsilons, beta_epsilons, 
                noise_parameters, world_EIGs, max_observation)


# set stimuli-related parameters 
features_df <- tibble(
  n_features = c(1), 
  on_features_n = c(1)
)
sequence_scheme = c("BBBBDB")

stims_df <- set_stim_params(sequence_scheme, features_df)


full_params_df <- make_simulation_params(n_sim = 100,
                                        model_params, 
                                        stims_df)

```

note: starts with 0 results in buggy behavior 

```{r}

tic()
all_sims_res <- full_params_df %>%
  mutate(row_number = row_number()) %>% 
  group_by(row_number) %>% 
  nest() %>%
  mutate(results = map(data,
                       function(df) main_simulation(params = df))) %>%
  unnest(cols = c(data, results))
toc()

```

```{r}
all_sims_res %>% 
  head()
```


observation: BBBBBB 

```{r}
all_sims_res %>% 
  mutate(prior_info = paste0("a", alpha_prior, "b", beta_prior)) %>% 
  group_by(row_number, prior_info, sub_id, stimulus_idx, sequence_scheme) %>% 
  summarise(sample_n = n()) %>% 
  #filter(sequence_scheme == "BBBBBBBB") %>% 
  ggplot(aes(x = stimulus_idx, y = sample_n)) + 
  #geom_point(alpha = .3) + 
  stat_summary(fun.data = "mean_cl_boot", geom = "line") + 
  facet_wrap(~prior_info)
```

```{r}
hab <- readRDS(here("dishab_sim_BBBBBB.RDS")) %>% 
  mutate(sequence_scheme = "BBBBBB") # a bug
dishab <- readRDS(here("dishab_sim_BBBBDB.RDS"))
```

```{r}
bind_rows(hab, dishab) %>% 
  mutate(prior_info = paste0("a", alpha_prior, "b", beta_prior)) %>% 
  group_by(row_number, prior_info, sub_id, stimulus_idx, sequence_scheme) %>% 
  summarise(sample_n = n()) %>% 
  #filter(sequence_scheme == "BBBBBBBB") %>% 
  ggplot(aes(x = stimulus_idx, y = sample_n, color = sequence_scheme)) + 
  #geom_point(alpha = .3) + 
  stat_summary(fun.data = "mean_cl_boot", geom = "pointrange", position = position_dodge(width = .5)) + 
   stat_summary(fun.data = "mean_cl_boot", geom = "line", position = position_dodge(width = .5)) +
  facet_wrap(~prior_info) + 
  theme_classic()
```


```{r}
sim <-  readRDS(here("model/cached_data/sim_res.RDS"))

```

```{r}
sim
```

```{r}
lk_table <- sim %>% 
  unnest(data) %>% 
  mutate(
    params_info = paste0("ep_", noise_parameter, "_wEIG_", 
                         world_EIG, "_of_", on_features_n)  
  ) %>% 
  select(row_number, params_info)

lk_table
```


```{r}
tidy_sim <- sim %>% 
  ungroup() %>% 
  select(row_number, res) %>% 
  unnest(cols = c(res)) %>% 
  unnest(res) %>% 
  select(!starts_with("f")) %>% 
  left_join(lk_table, by = "row_number") %>% 
  group_by(params_info, stimulus_idx) %>% 
  summarise(sample_n = n())
  
```


