---
title: "noisy sim"
output: html_notebook
---

# Preliminaries

```{r}
# library(reshape2)
library(tidyverse)
library(here)
library(matrixStats)
```

```{r}
## source relevant files
source(here("helper/get_stimuli.R"))
source(here("helper/get_observation.R"))
source(here("helper/grid_approximation.R"))
source(here("helper/noisy_update.R"))

source(here("helper/get_kl_eig.R"))

```

# set up  all the parameters 


```{r}
## stimuli related 
num_features = 2
num_features_simple = 1
trials_per_block = 8
deviant_positions = 4
dissimilarity_ratio = 0.2
epsilon = 0.1

## grid approximation related 
grid_theta <- seq(0.1, 1, 0.2)
grid_epsilon <- seq(0.1, 1, 0.2)
alpha_prior = 1
beta_prior = 1
alpha_epsilon = 10 
beta_epsilon = 1

## eig related 
env_eig = 0.005
max_obs = 500

## experiment related 
subject_n = 10
```


# generate stimuli

```{r}


# must satisfy: total feature > (1 + dissimilar ratio) * featureOnumber
simple_stimuli <- generate_creature_sequence(
  block_length = trials_per_block, 
  deviant_positions = deviant_positions,  # takes a vector, 
  total_feature = num_features, 
  feature_theta = 0.8, 
  feature_number = num_features_simple, 
  dissimilar_ratio = dissimilarity_ratio)
```


# main simulation (sketchy)
```{r}
main_simulation <- function(
                          subject, 
                          stimuli_sequence, 
                          noise_parameter, 
                          eig_from_world = .005,
                          max_observation = 500, # should this be per trial or in total? currently in total 
                          grid_theta = grid_theta, 
                          grid_epsilon = grid_epsilon, 
                          alpha_prior = alpha_prior, 
                          beta_prior = beta_prior,
                          alpha_epsilon = alpha_epsilon, 
                          beta_epsilon = beta_epsilon
                          ){
  
  # set up the df that tracks eig  
  df <- tibble(t = rep(NA,max_observation),
             stimulus_idx = rep(NA,max_observation), 
             EIG = rep(NA,max_observation), 
             p_look_away = rep(NA,max_observation), 
             look_away = rep(NA,max_observation))

  
  # set up the df that keep trakc of observation 
  observations <-  stimuli_sequence %>% 
    # create an empty dataframe with all the info needed to be tracked 
    filter(is.na(.)) %>% 
    mutate(t = NA_integer_) 
  
  
  # the total number of stimuli 
  total_trial_number = nrow(stimuli_sequence)
  total_feature_number = stimuli_sequence %>% 
    select(starts_with("V")) %>% 
    ncol()
  


  # which stimulus are we looking at
    stimulus_idx <- 1
    t <- 1
  
  
  while(stimulus_idx <= total_trial_number){
    
    current_stimulus <- stimuli_sequence %>% 
      filter(trial_number == stimulus_idx)
    
    current_observation <- noisy_observation_creature(
                                stimuli_df = stimuli_sequence,
                                trial_index  = stimulus_idx, 
                                n_sample = 1, 
                                epsilon = noise_parameter
                              )
    
    # add to current observation 
    observations <- bind_rows(observations, 
                              current_observation %>% mutate(
                                trial_number = stimulus_idx, 
                                trial_type = current_stimulus$trial_type,
                                t = t))
    
    # calculate posterior at t 
    # optimization possible!
    posterior_at_t <- grid_apprxoimation_with_observation(
                          noisy_observation = observations, 
                          track_epsilon = TRUE, 
                          grid_theta = grid_theta, 
                          grid_epsilon = grid_epsilon, 
                          alpha_prior = alpha_prior, 
                          beta_prior = beta_prior,
                          alpha_epsilon = alpha_epsilon, 
                          beta_epsilon = beta_epsilon
                        )
    

    
    # maybe needs scaling?
    
    df$t[t] = t
    df$stimulus_idx[t] = stimulus_idx
    
    df$EIG[t] = get_eig(current_observation, 
                    observations, 
                    posterior_at_t, 
                    grid_theta = grid_theta, 
                    grid_epsilon = grid_epsilon, 
                    alpha_prior = alpha_prior, 
                    beta_prior = beta_prior,
                    alpha_epsilon = alpha_epsilon, 
                    beta_epsilon = beta_epsilon)
    
    # flip a coin with p_keep_looking weight
    df$p_look_away[t] = eig_from_world / (df$EIG[t] + eig_from_world)
    df$look_away[t] = rbinom(1, 1, prob = df$p_look_away[t]) == 1

    if (df$look_away[t]==TRUE) {
      stimulus_idx <- stimulus_idx + 1
    }
    
    t <- t + 1 
      
      
  }
    
  df <- df %>% mutate(id = subject)
  
  
  return(df)
}
```


```{r}

sims <- lapply(seq(1, subject_n, 1), 
         function(x){
           main_simulation(subject = x,
                          stimuli_sequence = simple_stimuli, 
                          noise_parameter = epsilon, 
                          eig_from_world = env_eig,
                          max_observation = max_obs, # should this be per trial or in total? currently per trial 
                          grid_theta = grid_theta, 
                          grid_epsilon = grid_epsilon, 
                          alpha_prior = alpha_prior, 
                          beta_prior = beta_prior,
                          alpha_epsilon = alpha_epsilon, 
                          beta_epsilon = beta_epsilon)
         }
  ) %>% 
    bind_rows()
```

```{r}
sims %>% 
  group_by(id, stimulus_idx) %>% 
  drop_na() %>% 
  summarise(n_samps = n()) %>% 
  ggplot(aes(x = stimulus_idx, y = n_samps)) + 
  geom_point() + 
  geom_vline(xintercept = c(3, 5))
```

```{r}
sims %>% 
  ggplot(aes(x = t, y = EIG, group = id)) + 
  geom_line(alpha = .3)

sims %>% 
  ggplot(aes(x = t, y = EIG, group = id)) + 
  geom_line(alpha = .3) + 
  facet_wrap(~stimulus_idx)

sims %>% 
  ggplot(aes(x = t, y = EIG)) + 
  geom_line(alpha = .3) + 
  facet_wrap(~id)

# trial level eig doesn't make sense?
sims %>% 
  group_by(id, stimulus_idx) %>% 
  summarise(trial_EIG = sum(EIG)) %>% 
  ggplot(aes(x = stimulus_idx, 
             y = trial_EIG, 
             group = id)) + 
  geom_line(alpha = .3)
```

# optimization 
```{r}
library([lineprof)
```


