---
title: "timing"
author: "anjie"
date: "5/18/2022"
output: html_document
---

```{r}
library(here)
library(tictoc)
library(tidyverse)
library(matrixStats)
source(here("helper/compute_prob.r"))
source(here("helper/granch_main_simulation_helper.R")) # this will import other helper functions 
source(here("helper/granch_sim_setup_helper.R")) # this will import functions that help with setting parameters 
```

# prior df 

```{r}

time_prior_calculation <- function(grid_mu_n, grid_sig_sq_n, grid_y_n, grid_epsilon_n, 
                                   hypothetical_obs_grid_n){
  mu_priors = c(0)
  mu_priors = c(0)
  V_priors = c(0.001)
  alpha_priors = c(1) 
  beta_priors = c(1) 
  epsilons = c(0.000001) 
  mu_epsilon = c(0.001)
  sd_epsilon = c(2)
  world_EIGs = c(0.0001) 
  max_observation = 500
  
  grid_mu_theta = seq(-2, 2, 4/grid_mu_n)
  grid_sig_sq = seq(-2, 2, 4/grid_sig_sq_n)
  grid_y = seq(-2, 2, 4/grid_y_n)
  grid_epsilon = seq(-2, 2, 4/grid_epsilon_n)
  hypothetical_obs_grid_n = hypothetical_obs_grid_n
  
  model_params <- set_granch_params(
                grid_mu_theta, grid_sig_sq, grid_y, grid_epsilon, hypothetical_obs_grid_n,
                mu_priors, V_priors, 
                alpha_priors, beta_priors, 
                epsilons, mu_epsilon, sd_epsilon,
                world_EIGs, max_observation)

  startTime <- Sys.time()
  model_params <- add_precalculated_prior_dfs(model_params)
  endTime <-  Sys.time()

  info_df <- tibble(
    time = c(endTime - startTime), 
    len_grid_mu_theta = length(grid_mu_theta), 
    len_grid_sig_sq = length(grid_sig_sq), 
    len_grid_y = length(grid_y), 
    len_grid_epsilon = length(grid_epsilon), 
    hypothetical_obs_grid_number = hypothetical_obs_grid_n,
    prior_grid_row = nrow(model_params$prior_df[[1]]),
    df_y_given_mu_sig_sq_row = nrow(model_params$df_y_given_mu_sig_sq[[1]]),
    obj_size = object.size(model_params)
  )
  return (info_df)
}

time_prior_calculation(2, 2, 1, 1, 2)
```


```{r}
time_prior_df <- tibble(
  grid_mu_n = seq(1, 10, 1), 
  grid_sig_sq_n = seq(1, 10, 1),
  grid_y_n = seq(1, 10, 1), 
  grid_epsilon_n = seq(1, 10, 1), 
  hypothetical_obs_grid_n = seq(1, 10, 1)
) %>% 
  mutate(df = pmap(., time_prior_calculation)) %>% 
  unnest(df)

```

```{r}
time_prior_df
```

```{r}
time_prior_df %>% 
  mutate(time = as.numeric(time), obj_size = as.numeric(obj_size)) %>% 
  pivot_longer(cols = c("time", "obj_size"), 
               names_to = 'type', 
               values_to = "value") %>% 
  ggplot(aes(x = prior_grid_row, 
             y = value, 
             color = type)) + 
  geom_point()+ 
  geom_line() +
  geom_smooth(method = "lm") + 
  facet_wrap(~type, scales = "free")

time_prior_df %>% 
  mutate(time = as.numeric(time), obj_size = as.numeric(obj_size)) %>% 
  pivot_longer(cols = c("time", "obj_size"), 
               names_to = 'type', 
               values_to = "value") %>% 
  ggplot(aes(x = len_grid_mu_theta, 
             y = value, 
             color = type)) + 
  geom_point()+ 
  geom_line() + 
  facet_wrap(~type, scales = "free")
```
```{r}
lmodel <- lm(as.numeric(time) ~ prior_grid_row, time_prior_df)

p = as.data.frame(100^3)
colnames(p) = "prior_grid_row"
predict(lmodel, newdata = p) / 3600
```



```{r}
 mu_priors = c(0)
  mu_priors = c(0)
  V_priors = c(0.001)
  alpha_priors = c(1) 
  beta_priors = c(1) 
  epsilons = c(0.000001) 
  mu_epsilon = c(0.001)
  sd_epsilon = c(2)
  world_EIGs = c(0.0001) 
  max_observation = 500
  
  grid_mu_theta = seq(-2, 2, 4/2)
  grid_sig_sq = seq(-2, 2, 4/2)
  grid_y = seq(-2, 2, 4/2)
  grid_epsilon = seq(-2, 2, 4/2)
  hypothetical_obs_grid_n = 2
  
  model_params <- set_granch_params(
                grid_mu_theta, grid_sig_sq, grid_y, grid_epsilon, hypothetical_obs_grid_n,
                mu_priors, V_priors, 
                alpha_priors, beta_priors, 
                epsilons, mu_epsilon, sd_epsilon,
                world_EIGs, max_observation)

model_params <- add_precalculated_prior_dfs(model_params)

```

```{r}
# 5 columns 
dim(model_params$prior_df[[1]])

n_row = (2^31) - 1
df <- tibble(
  "a" = rep(1, n_row), 
  "b" = rep(1, n_row), 
  "c" = rep(1, n_row), 
  "d" = rep(1, n_row), 
  "e" = rep(1, n_row)
)
```

# prior df + simulation 

```{r}
time_granch_simulation <- function(embedding_path, grid_mu_n, grid_sig_sq_n, grid_y_n, grid_epsilon_n, 
                                   hypothetical_obs_grid_n, 
                                   n_feature){

  
  embedding_path <- embedding_path
  stimuli_pool_size <- 10
  stimuli_pool <-  get_stimuli_pool(stimuli_pool_size, n_feature, embedding_path)

  
    mu_priors = c(0)
  mu_priors = c(0)
  V_priors = c(0.001)
  alpha_priors = c(1) 
  beta_priors = c(1) 
  epsilons = c(0.000001) 
  mu_epsilon = c(0.001)
  sd_epsilon = c(2)
  world_EIGs = c(0.0001) 
  max_observation = 500
  
  grid_mu_theta = seq(-2, 2, 4/grid_mu_n)
  grid_sig_sq = seq(-2, 2, 4/grid_sig_sq_n)
  grid_y = seq(-2, 2, 4/grid_y_n)
  grid_epsilon = seq(-2, 2, 4/grid_epsilon_n)
  hypothetical_obs_grid_n = hypothetical_obs_grid_n
  
  model_params <- set_granch_params(
                grid_mu_theta, grid_sig_sq, grid_y, grid_epsilon, hypothetical_obs_grid_n,
                mu_priors, V_priors, 
                alpha_priors, beta_priors, 
                epsilons, mu_epsilon, sd_epsilon,
                world_EIGs, max_observation)

  startTime <- Sys.time()
  model_params <- add_precalculated_prior_dfs(model_params)
  endTime <-  Sys.time()

  info_df <- tibble(
    time_for_prior = c(endTime - startTime), 
    len_grid_mu_theta = length(grid_mu_theta), 
    len_grid_sig_sq = length(grid_sig_sq), 
    len_grid_y = length(grid_y), 
    len_grid_epsilon = length(grid_epsilon), 
    hypothetical_obs_grid_number = hypothetical_obs_grid_n,
    prior_grid_row = nrow(model_params$prior_df[[1]]),
    df_y_given_mu_sig_sq_row = nrow(model_params$df_y_given_mu_sig_sq[[1]]),
    obj_size = object.size(model_params)
  )
  
  stims_df <- tibble(sequence_scheme = c("BBBBBB"),
                   n_features = n_feature
                   ) %>% 
    mutate(
    stimuli_sequence = map(sequence_scheme, function(ss){make_real_stimuli_df(ss, 
                                                                              background = get_bd_pair(stimuli_pool)[1, ], 
                                                                              deviant = get_bd_pair(stimuli_pool)[2, ])}))



  full_params_df <- make_simulation_params(n_sim = 1,model_params, stims_df)

  startTime <- Sys.time()
  all_sims_res <- full_params_df %>%
  mutate(row_number = row_number()) %>% 
  group_by(row_number) %>% 
  nest() %>%
  mutate(results = map(data,
                       function(df) granch_main_simulation(params = df))) %>%
  unnest(cols = c(data, results))
  endTime <-  Sys.time()
  
  info_df <- info_df %>% 
    mutate(ranch_sim_time = endTime - startTime, 
           n_f = n_feature, 
           n_hypo_obs = hypothetical_obs_grid_n)
  
  return (info_df)
}
```

```{r}
```

```{r}
time_granch_df <- tibble(
  embedding_path = embedding_path, 
  grid_mu_n = seq(1, 1, 1), 
  grid_sig_sq_n = seq(1, 1, 1),
  grid_y_n = seq(1, 1, 1), 
  grid_epsilon_n = seq(1, 1, 1), 
  hypothetical_obs_grid_n = seq(2, 2, 1), # must be greater or equal to 2
  n_feature = seq(1, 5, 1), 
) %>% 
  mutate(df = pmap(., time_granch_simulation)) %>% 
  unnest(df)
```

```{r}
time_granch_df <- tibble(
   embedding_path = embedding_path, 
  grid_mu_n = seq(1, 4, 1), 
  grid_sig_sq_n = seq(1, 4, 1),
  grid_y_n = seq(1, 4, 1), 
  grid_epsilon_n = seq(1, 4, 1)
) %>% 
  crossing(
    n_feature = seq(1, 5, 1), 
    hypothetical_obs_grid_n = seq(2, 5, 1), 
  )
  
time_granch_df
```



```{r}
time_granch_df %>% 
  ggplot(aes(x = n_f, y = ranch_sim_time)) + 
  geom_point() + 
  geom_line()
```

# from cluster

```{r}
df <- list.files(here("cluster_granch/cached_res/"), pattern = ".RDS") %>% 
  sapply(., function(x) paste0(here("cluster_granch/cached_res/"), x)) %>% 
  map(readRDS) %>% 
  bind_rows()
```


```{r}

df %>% 
  ggplot(aes(x = n_f, y = ranch_sim_time, 
             color = as.factor(prior_grid_row) 
             )) + 
  geom_point() + 
  geom_line()
```



```{r}
# basically we want to know x & c_nf's values 
runtime_fit <- function(s, x, c_nf, n_f, grid_row){
  return (s * ((grid_row *x) ^ (c_nf * n_f)))
  #return ((grid_row * ((x) ^ n_f)))
}

t <- tibble(
  s = 10,
  x = 0.9798673, 
  c_nf = 0.2384108, 
  n_f = seq(1:5)
) %>% 
  crossing( 
  grid_row = c(2, 12, 36)) %>% 
  mutate(t = unlist(pmap(., runtime_fit) ))


t %>% 
  ggplot(aes(x = n_f, y = t , 
             color = as.factor(grid_row)
             )) + 
  geom_point() + 
  geom_line()

```


```{r}
data_vs_runtime_fit <- function(s, x, c_nf, n_f, grid_row, real_t){
  predicted_t <- runtime_fit(s, x, c_nf, n_f, grid_row)
  RMSE <- sum(sqrt((predicted_t - real_t) ^ 2))
  return(RMSE)
}

optim_runtime_fit_wrapper <- function(params){
  return(data_vs_runtime_fit(s = params[1],
                             x = params[2], 
                             c_nf = params[3], 
                             n_f = df$n_f,
                             grid_row = df$prior_grid_row, 
                             real_t = as.numeric(df$ranch_sim_time)))
  
}

#optim(c(1, 2, 5), optim_runtime_fit_wrapper)

optim_res<- optim(c(8, 1, .8), optim_runtime_fit_wrapper)
```


```{r}
t <- tibble(
  s =  optim_res$par[1], 
  x = optim_res$par[2], 
  c_nf =  optim_res$par[3], 
  n_f = seq(1:5)
) %>% 
  crossing( 
  grid_row = c(2, 12, 36)) %>% 
  mutate(t = unlist(pmap(., runtime_fit) ))


t %>% 
  ggplot(aes(x = n_f, y = 4* t, 
             color = as.factor(grid_row)
             )) + 
  geom_point() + 
  geom_line()

```





# limits for prior calc 


```{r}
#(input_x, input_sig_sq, mu, lambda, alpha, beta, log = TRUE)
input_x <- seq(-1, 1, .1)
input_sig_sq <- seq(-1, 1, .1)
mu <- seq(-1, 1, .5)
lambda <- seq(-1, 1, .5)
alpha <- seq(-1, 1, .5)
beta <- seq(-1, 1, .5)


dfs <- crossing(input_x, input_sig_sq, mu, lambda, alpha, beta)
safer_score <- possibly(score_mu_sig_sq, otherwise = "Calculation Error")

res <- pmap_df(dfs, safer_score)
```


```{r}
saveRDS(res, "prior_calc.rds")
```

