---
title: "debugging_mainsim"
author: "anjie"
date: "7/12/2021"
output: html_document
---

```{r}
library(tidyverse)
library(here)
library(matrixStats)
library(profvis)
library(microbenchmark)
source(here("helper/get_stimuli.R"))
source(here("helper/get_observation.R"))
source(here("helper/grid_approximation.R"))
source(here("helper/noisy_update.R"))
source(here("helper/main_simulation_under_construction.R"))
source(here("helper/get_eig_faster.R"))

```

```{r}
num_features = 1
num_features_simple = 1
num_feature_complex = 6
trials_per_block = 3
deviant_positions = 2
feature_theta = 0.9
dissimilarity_ratio = 0.9
noise_parameter = 0.1
## grid approximation related 
grid_theta <- seq(0.1, 1, 0.2)
grid_epsilon <- seq(0.1, 1, 0.2)
alpha_theta = 1
beta_theta = 1
alpha_prior = 5
beta_prior = 1
alpha_epsilon = 10 
beta_epsilon = 1
## eig related 
env_eig = 0.005
max_obs = 500

simple_stimuli <- generate_creature_sequence(
  block_length = trials_per_block, 
  deviant_positions = deviant_positions,  # takes a vector, 
  total_feature = num_features, 
  feature_theta = feature_theta, 
  feature_number = num_features_simple, 
  dissimilar_ratio = dissimilarity_ratio)
multifeature_stimuli <- generate_creature_sequence(block_length = trials_per_block, 
  deviant_positions = deviant_positions,  # takes a vector, 
  total_feature = 3, 
  feature_theta = feature_theta, 
  feature_number = num_features_simple, 
  dissimilar_ratio = dissimilarity_ratio)
```


```{r}
new_main_sims <- main_simulation_uc(subject = 1,
                stimuli_sequence = multifeature_stimuli, 
                noise_parameter = noise_parameter, 
                eig_from_world = 0.001,
                max_observation = 500, # should this be per trial or in total? currently per trial 
                grid_theta = grid_theta, 
                grid_epsilon = grid_epsilon, 
                alpha_prior = alpha_prior, 
                beta_prior = beta_prior,
                alpha_epsilon = alpha_epsilon, 
                beta_epsilon = beta_epsilon, 
                forced_exposure = TRUE,
                forced_sample = 5,
                optimize = FALSE)

```











