---
title: "fam preference"
author: "anjie"
date: "6/24/2021"
output: html_document
---

```{r}
library(tidyverse)
library(here)
library(matrixStats)
library(profvis)

source(here("helper/get_stimuli.R"))
source(here("helper/get_observation.R"))
source(here("helper/grid_approximation.R"))
source(here("helper/noisy_update.R"))
source(here("helper/main_simulation.R"))
source(here("helper/get_kl_eig.R"))
```

```{r parameter}
num_features = 1
num_features_simple = 1
num_feature_complex = 6
trials_per_block = 3
deviant_positions = 2
feature_theta = 0.9
dissimilarity_ratio = 0.2
noise_parameter = 0.1

## grid approximation related 
grid_theta <- seq(0.1, 1, 0.2)
grid_epsilon <- seq(0.1, 1, 0.2)
alpha_prior = 1
beta_prior = 1
alpha_epsilon = 10 
beta_epsilon = 1

## eig related 
env_eig = 0.005
max_obs = 500

## experiment related 
subject_n = 10

simple_stimuli <- generate_creature_sequence(
  block_length = trials_per_block, 
  deviant_positions = deviant_positions,  # takes a vector, 
  total_feature = num_features, 
  feature_theta = feature_theta, 
  feature_number = num_features_simple, 
  dissimilar_ratio = dissimilarity_ratio)
simple_stimuli$V1 <- c(TRUE, FALSE, TRUE)
simple_stimuli
```

# Relationships between EIG of environment and the looking time curves 
```{r}
env_eigs <- seq(0, 0.01, 0.001) 

  
  
eigs_sims <- lapply(env_eigs, 
       function(x){
         main_simulations(
                          subject_n, 
                          observation_assumption = "independent",
                          stimuli_sequence = simple_stimuli, 
                          noise_parameter = noise_parameter, 
                          eig_from_world = x,
                          max_observation = max_obs, # should this be per trial or in total? currently per trial 
                          grid_theta = grid_theta, 
                          grid_epsilon = grid_epsilon, 
                          alpha_prior = alpha_prior, 
                          beta_prior = beta_prior,
                          alpha_epsilon = alpha_epsilon, 
                          beta_epsilon = beta_epsilon)
       }
) %>% 
  bind_rows()



```

```{r}
saveRDS(eigs_sims, file = "varying_eigs.RDS")


```

```{r}
eigs_sims %>% 
  drop_na() %>% 
  group_by(stimulus_idx, id, EIG_from_world) %>% 
  summarise(n = n()) %>% 
  filter(n < 500) %>% 
  ggplot(aes(x = stimulus_idx, y = n, group = EIG_from_world, color = EIG_from_world)) + 
  stat_summary(fun.data = "mean_cl_boot") +  
  stat_summary(fun.data = "mean_cl_boot", geom = "line") + 
  facet_wrap(~EIG_from_world)


eigs_sims %>% 
  drop_na() %>%
  group_by(stimulus_idx, id, EIG_from_world) %>% 
  summarise(n = n()) %>% 
    filter(n < 500) %>% 
  mutate(stimulus_idx = as.factor(stimulus_idx)) %>% 
  ggplot(aes(x = EIG_from_world, y = n, color = stimulus_idx)) + 
  geom_point(position = "jitter") + 
  geom_smooth(method = "lm")

```



# Forced short exposure duration 
trying out the eig = 0.001, forced short exposure = 5 samples, eyeballed from graph above 

```{r}
num_features = 1
num_features_simple = 1
num_feature_complex = 6
trials_per_block = 3
deviant_positions = NULL
feature_theta = 0.9
dissimilarity_ratio = 0.2
noise_parameter = 0.1

## grid approximation related 
grid_theta <- seq(0.1, 1, 0.2)
grid_epsilon <- seq(0.1, 1, 0.2)
alpha_prior = 1
beta_prior = 1
alpha_epsilon = 10 
beta_epsilon = 1

## eig related 
env_eig = 0.001
max_obs = 100

## experiment related 
subject_n = 400
rep_stimuli <- generate_creature_sequence(
  block_length = trials_per_block, 
  deviant_positions = deviant_positions,  # takes a vector, 
  total_feature = num_features, 
  feature_theta = feature_theta, 
  feature_number = num_features_simple, 
  dissimilar_ratio = dissimilarity_ratio)

rep_stimuli
diff_stimuli <- rep_stimuli %>% mutate(V1 = c("TRUE", "FALSE", "TRUE"))
diff_stimuli
```


```{r}
subject_n = 200
fs_sim_same <- main_simulations(
                          subject_n, 
                          observation_assumption = "independent",
                          stimuli_sequence = rep_stimuli, 
                          noise_parameter = noise_parameter, 
                          eig_from_world = env_eig,
                          max_observation = max_obs, # should this be per trial or in total? currently per trial 
                          grid_theta = grid_theta, 
                          grid_epsilon = grid_epsilon, 
                          alpha_prior = alpha_prior, 
                          beta_prior = beta_prior,
                          alpha_epsilon = alpha_epsilon, 
                          beta_epsilon = beta_epsilon, 
                          exposure_type = "forced_short")


fs_sim_diff <-  main_simulations(
                          subject_n, 
                          observation_assumption = "independent",
                          stimuli_sequence = diff_stimuli, 
                          noise_parameter = noise_parameter, 
                          eig_from_world = env_eig,
                          max_observation = max_obs, # should this be per trial or in total? currently per trial 
                          grid_theta = grid_theta, 
                          grid_epsilon = grid_epsilon, 
                          alpha_prior = alpha_prior, 
                          beta_prior = beta_prior,
                          alpha_epsilon = alpha_epsilon, 
                          beta_epsilon = beta_epsilon, 
                          exposure_type = "forced_short")


```

```{r}

saveRDS(fs_sim_same, file = "fs_sim_same_200.Rds")
saveRDS(fs_sim_diff, file = "fs_sim_diff_200.Rds")


tidy_sims_df <- function(sims_df){
  sims_df %>% 
    drop_na() %>% 
    group_by(stimulus_idx, id) %>% 
    summarise(sample_n = n()) 
  
}

tidy_same_sim_df <- fs_sim_same %>% 
  tidy_sims_df() %>% 
  mutate(type = "second_background")

tidy_diff_sim_df <- fs_sim_diff %>% 
  tidy_sims_df() %>% 
  mutate(type = "second_deviant")

comparison_Df <- bind_rows(tidy_same_sim_df, 
                           tidy_diff_sim_df)
```

```{r}
comparison_Df %>% 
  ggplot(aes(x = stimulus_idx, y = sample_n, color = type)) +
  geom_jitter(width = .1, alpha = .1) + 
  stat_summary(fun.data = "mean_cl_boot") +  
  stat_summary(fun.data = "mean_cl_boot", geom = "line") + 
  theme_classic()
  
```



```{r}
#saveRDS(fs_sims, file = "fs_sims_400.Rds")
fs_sims_400 <- readRDS(here("m2_noisy_feature_learning/fs_sims_400.Rds"))
fs_sims_400 %>% 
  group_by(stimulus_idx, id) %>% 
  drop_na() %>% 
  summarise(n = n()) %>% 
  ggplot(aes(x = stimulus_idx, y = n)) + 
  geom_jitter(width = .3, alpha = .2, color = "blue")+ 
  stat_summary(fun.data = "mean_cl_boot") +  
  stat_summary(fun.data = "mean_cl_boot", geom = "line") + 
  theme_classic()
```

## different combination of forced short sample n and the expected environment gain 

```{r}
subject_n = 10
env_eigs <- seq(0.001, 0.005, 0.001)
forced_samples <- seq(1, 8, 1)


params <- expand_grid(env_eig = env_eigs, forced_sample = forced_samples)

eig_fs_sims <- map2_dfr(params$env_eig, 
    params$forced_sample, 
    function(x, y){
      main_simulations(
                          subject_n, 
                          observation_assumption = "independent",
                          stimuli_sequence = rep_stimuli, 
                          noise_parameter = noise_parameter, 
                          eig_from_world = x,
                          max_observation = max_obs, # should this be per trial or in total? currently per trial 
                          grid_theta = grid_theta, 
                          grid_epsilon = grid_epsilon, 
                          alpha_prior = alpha_prior, 
                          beta_prior = beta_prior,
                          alpha_epsilon = alpha_epsilon, 
                          beta_epsilon = beta_epsilon, 
                          exposure_type = "forced_short",
                          forced_sample = y)
    })


```

```{r}
saveRDS(eig_fs_sims, file = "eig_fs_sims_10.Rds")

```

```{r}
eig_fs_sims %>% 
   drop_na() %>% 
    group_by(stimulus_idx, id, forced_sample_n, EIG_from_world) %>%  
  summarise(sample_n = n()) %>% 
  filter(EIG_from_world ==  0.001) %>% 
  ggplot(aes(x = stimulus_idx, y = sample_n)) +
  geom_jitter(width = .3, alpha = .3) + 
  stat_summary(fun.data = "mean_cl_boot") +  
  stat_summary(fun.data = "mean_cl_boot", geom = "line") + 
  theme_classic() + 
  facet_wrap(~forced_sample_n)

eig_fs_sims %>% 
   drop_na() %>% 
    group_by(stimulus_idx, id, forced_sample_n, EIG_from_world) %>%  
  summarise(sample_n = n()) %>% 
  filter(EIG_from_world ==  0.005) %>% 
  ggplot(aes(x = stimulus_idx, y = sample_n)) +
  geom_jitter(width = .3, alpha = .3) + 
  stat_summary(fun.data = "mean_cl_boot") +  
  stat_summary(fun.data = "mean_cl_boot", geom = "line") + 
  theme_classic() + 
  facet_wrap(~forced_sample_n)
  
```



# Forced long exposure 