---
title: "toy example"
author: "anjie & gal "
date: "6/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(microbenchmark)
library(tidyverse )
```

# performance difference? 

adapt this code: 
https://www.analyticskhabar.com/apply-vs-lapply-vs-mapply-vs-tapply-vs-sapply/

```{r}

create_df_tibble  <- function(nrow){
  base_df <- tibble(
  "one" = rep(1, nrow), 
  "two" = rep(2, nrow))

}


#expand_function <- function()
  
num <- 10000
t <- create_df_tibble(num) 
```

# add row to df
```{r}

l <- bind_rows(t, tibble_row())
new <- t[1,]
l[11,] <- new

l

add_new_row <- function(){
  l[num+1, ] <- new
}
```


```{r}
```

# avoid pull operation at all costs 

maybe we want to revert all select back to base r syntax 
=> select is bad, maybe
```{r}
microbenchmark( add_new_row(),
                bind_rows(t, tibble_row()),
                rownames(t),
                row_number(t),
                a <- t['one'],
                a <-  t %>% select(one),
                a <- t$one,
                a <- t %>% pull(one),
                t$three <- t$two + 1,
                a <- t %>% mutate(three = two + 1),
                a <- t %>% filter(one == 1), 
                a <- t[t$one == 1,],
              times = 10)

```

# sum in r 
```{r}
l <- seq(1, 1000000000, 1)

microbenchmark( sum(l),
                matrixStats::sum2(l),
              times = 10)

```

# pipeline 
```{r}
library(bench)
library(magrittr)


bm <- bench::mark(
   x <- t[startsWith(names(t), "V")],
   x <- t %>% select(starts_with("V"))
)
ggplot2::autoplot(bm)
```

```{r}
df <- tibble("char" = c("a", "a", "b", "b"), 
             "num" = c(1, 1, 1, 1))



bm <- bench::mark(
   x <- df %>% group_by(char) %>% summarise(sum = sum(num)),
   
)
ggplot2::autoplot(bm)

microbenchmark(
   x <- df %>% group_by(char) %>% summarise(sum = sum(num)),
   x <- aggregate(df$num,             # Sum by group
          by = list(df$char),
          FUN = sum),
   times = 100
)
```

## 
```{r}
pos_old <- function(posterior_df){
  posterior_df %>% 
          group_by(theta) %>%
          summarise(log_posterior = matrixStats::logSumExp(log_posterior)) %>%
          mutate(posterior = exp(log_posterior))
}

pos_new <- function(posterior_df, tibble = TRUE){
  pos_new <- setNames(aggregate(posterior_df$log_posterior,             # Sum by group
          by = list(posterior_df$theta),
          FUN = matrixStats::logSumExp), 
         c("theta", "log_posterior"))

  pos_new$posterior <- exp(pos_new$log_posterior)
  if(tibble){
    return (as_tibble(pos_new))
  }
  return(pos_new)
}

bm <- bench::mark(
   pos_old(posterior_df),
   pos_new(posterior_df, TRUE), 
   pos_new(posterior_df, FALSE),
   check = FALSE#because df difference 
)
ggplot2::autoplot(bm)

```

## speed test for posterior df 
```{r}
simple_stimuli <- generate_creature_sequence(
  block_length = trials_per_block, 
  deviant_positions = deviant_positions,  # takes a vector, 
  total_feature = 5, 
  feature_theta = feature_theta, 
  feature_number = num_features_simple, 
  dissimilar_ratio = dissimilarity_ratio)

observations <- noisy_observation_creature(simple_stimuli, 
                                           1, 
                                           n_sample = 10, 
                                           epsilon = 0.8)



old_grid <- function(){
  posterior_at_t <- grid_apprxoimation_with_observation(
        noisy_observation = observations, 
        track_epsilon = TRUE, 
        grid_theta = grid_theta, 
        grid_epsilon = grid_epsilon, 
        alpha_prior = alpha_prior, 
        beta_prior = beta_prior,
        alpha_epsilon = alpha_epsilon, 
        beta_epsilon = beta_epsilon, 
        optimize = FALSE
      )
  
}
new_grid <- function(){
  posterior_at_t <- grid_apprxoimation_with_observation(
        noisy_observation = observations, 
        track_epsilon = TRUE, 
        grid_theta = grid_theta, 
        grid_epsilon = grid_epsilon, 
        alpha_prior = alpha_prior, 
        beta_prior = beta_prior,
        alpha_epsilon = alpha_epsilon, 
        beta_epsilon = beta_epsilon, 
        optimize = TRUE
      )
  
}

bm <- bench::mark(
  old_grid(), 
  new_grid()
)
ggplot2::autoplot(bm)
```



# operation on each feature 

```{r}
df_lapply_operation <- function(df){
  
  res <- lapply(seq(1, ncol(df), 1), 
         
         function(x){
           y <- tibble((df[,x]) + 1)
         }
         ) %>% 
      bind_rows()
  
  return(res)
}


df_sapply_operation <- function(df){
  
  res <- sapply(seq(1, ncol(df), 1), 
         
         function(x){
           y <- tibble((df[,x]) + 1)
         }
         ) %>% 
      bind_rows()
  
  return(res)
}

df_mapply_operation <- function(df){
  
  res <- mapply(
         
         function(x, y){
           x+y
         }, 
        df$one, df$two         
         ) 

  return(res)
}

df_lapply_operation(t)

microbenchmark(df_lapply_operation(t),
               df_sapply_operation(t),
               df_mapply_operation(t),
              times = 100)

```

```{r}
a <- seq(1, 99, 1)
b <- seq(1, 99, 1)

exp_g  <- function(m, n){
  a <- seq(1, m, 1)
  b <- seq(1, n, 1)
  res <- tidyr::expand_grid(a = a, 
                     b = b)
  return (res)
}

allocate <- function(m, n){
  df <- tibble("a" = seq(1))
  
}

microbenchmark(
  
  exp_g(10, 10),
              times = 100)
```

