---
title: "Fitting model to data"
author: "anjie"
date: "8/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(matrixStats)


source(here("helper/make_scheme_and_params.r"))
source(here("helper/get_eig_faster.R"))
source(here("helper/get_stimuli.R"))
source(here("helper/get_observation.R"))
source(here("helper/main_simulation_under_construction.r"))
source(here("helper/params_helper_experiment.r"))


d <- read_csv(here("data/processed_rt_task_data.csv"))


```

# figuring out the sequece and generate the stimuli sequence with allt he parameters 


```{r}

alpha_epsilon = c(1)
beta_epsilon = c(1)
alpha_priors = c(1, 50)
beta_priors = c(1,50)
noise_parameters = c(0.001, 0.005)
eigs_from_world = c(0.001,0.005)
max_observation = 500
fixed_length_complexity = TRUE 
feature_space_n = 7
simple_feature_n = 1
complex_feature_n = 3
dissimilar_ratio = 1
sequence_scheme = c("BDBBBB", "BBBDBB", "BBBBBD", "BBBBBB")
complexity = c("complex", "simple")

full_params_df <- make_simulation_params(
                                   sequence_scheme, 
                                   complexity, 
                                   alpha_priors, 
                                   beta_priors, 
                                   alpha_epsilon, 
                                   beta_epsilon, 
                                   noise_parameter, 
                                   eig_from_world, 
                                   max_observation, 
                                   fixed_length_complexity, 
                                   feature_space_n, 
                                   simple_feature_n, 
                                   complex_feature_n, 
                                   dissimilar_ratio)

full_params_df

```




# running the simulation 



```{r}
grid_theta <- seq(0.1, 1, 0.2)
grid_epsilon <- seq(0.1, 1, 0.2)




run_all_sims <- function(full_params_df){
  
  
  params_id <- full_params_df %>% 
  distinct(params_id) %>% 
  select(params_id) %>% 
  pull()
  
  sim_use_params_df <- full_params_df %>% 
    select(params_id, sim_id, n, stimuli_sequence, noise_parameter, 
                               eig_from_world, max_observation, alpha_prior, beta_prior, alpha_epsilon, beta_epsilon)
  
  lapply(params_id, 
         function(id){
           pmap_dfr(sim_use_params_df %>% filter(params_id == id) %>% select(-c("params_id")), 
            simulation_wrapper_for_linking_data
            ) %>% 
             mutate(params_id = id)
         }) %>% 
    bind_rows()
  
}


all_sims_res <- run_all_sims(full_params_df)
saveRDS(all_sims_res, file = "premeetingrun.RDS")

```

```{r}
sim_res_only_deviant_last <- run_all_sims(full_params_df %>% filter(sequence_scheme == "BBBBBD"))

```


```{r}
alpha_epsilon = c(1)
beta_epsilon = c(1)
alpha_priors = c(1, 50)
beta_priors = c(1,50)
noise_parameters = c(0.001)
eigs_from_world = c(0.005)
max_observation = 500
fixed_length_complexity = FALSE 
feature_space_n = 10
simple_feature_n = 1
complex_feature_n = 5
dissimilar_ratio = 1



non_fixed_full_params_df <- make_simulation_params(alpha_priors, 
                                   beta_priors, 
                                   alpha_epsilon, 
                                   beta_epsilon, 
                                   noise_parameter, 
                                   eig_from_world, 
                                   max_observation, 
                                   fixed_length_complexity, 
                                   feature_space_n, 
                                   simple_feature_n, 
                                   complex_feature_n, 
                                   dissimilar_ratio)

all_sims_res <- run_all_sims(non_fixed_full_params_df)

```


# cleaning the simulation result to run correlation with the model 


```{r}
complete_sim_res <- all_sims_res %>% 
  group_by(params_id, sim_id, subject_id, stimulus_idx) %>% 
  summarise(sample_n = n()) %>% 
  filter(!is.na(stimulus_idx)) %>% 
  left_join(full_params_df %>% select(-n), by = c("params_id", "sim_id")) %>% 
  mutate(prior_info = paste("a", alpha_prior, "b", beta_prior, sep = "_")) %>% 
  mutate(eig_info = paste("np", noise_parameter, "ee", eig_from_world))


```




# import looking time 

```{r}
lt_df <- read_csv(here("data/processed_rt_task_data.csv"))

lt_df_cleaned <- lt_df %>% 
  group_by(deviant_position, block_type, trial_number, trial_type) %>% 
  summarise(
    mean_lt = mean(trial_looking_time),
    log_mean_lt = log(mean(trial_looking_time))
  ) %>% 
  mutate(
    sequence_scheme = case_when(
      deviant_position == 2 ~ "BDBBBB", 
      deviant_position == 4 ~ "BBBDBB", 
      deviant_position == 6 ~ "BBBBBD", 
      is.na(deviant_position) ~ "BBBBBB"
    ), 
    complexity = case_when(
      block_type == "complex_dissimilar" ~ "complex", 
      block_type == "simple_dissimilar" ~ "simple"
    )
  )
lt_df_cleaned
```

```{r}
lt_df_with_blocks <- lt_df %>% 
  group_by(deviant_position, block_type, block_number, trial_number, trial_type) %>% 
  summarise(
    mean_lt = mean(trial_looking_time),
    log_mean_lt = log(mean(trial_looking_time))
  ) %>% 
  mutate(
    sequence_scheme = case_when(
      deviant_position == 2 ~ "BDBBBB", 
      deviant_position == 4 ~ "BBBDBB", 
      deviant_position == 6 ~ "BBBBBD", 
      is.na(deviant_position) ~ "BBBBBB"
    ), 
    complexity = case_when(
      block_type == "complex_dissimilar" ~ "complex", 
      block_type == "simple_dissimilar" ~ "simple"
    )
  )

lt_df_with_blocks
```


```{r}
complete_sim_res %>% 
  group_by(params_id, stimulus_idx, sim_id, sequence_scheme, complexity, prior_info, eig_info) %>% 
  summarise(sample_n = mean(sample_n)) %>% 
  rename(trial_number = stimulus_idx) %>% 
  left_join(lt_df_cleaned, by = c("sequence_scheme", "complexity", "trial_number")) %>% 
  ggplot(aes(x = log(sample_n), y = log_mean_lt, color = trial_number)) + 
  geom_point()+ 
  geom_smooth(method = "lm") + 
  facet_wrap(eig_info~prior_info)


```

```{r}
complete_sim_res %>% 
   ggplot(aes(x = stimulus_idx, y = sample_n, color = complexity)) + 
  stat_summary(fun.data = "mean_cl_boot", geom = "pointrange",  position = position_dodge(width = .2)) +
  stat_summary(fun.data = "mean_cl_boot", geom = "line",  position = position_dodge(width = .2)) + 
  theme_classic() + 
  facet_grid(eig_info~sequence_scheme)

complete_sim_res %>% 
   ggplot(aes(x = stimulus_idx, y = sample_n, color = complexity)) + 
  stat_summary(fun.data = "mean_cl_boot", geom = "pointrange",  position = position_dodge(width = .2)) +
  stat_summary(fun.data = "mean_cl_boot", geom = "line",  position = position_dodge(width = .2)) + 
  theme_classic() + 
  facet_grid(prior_info ~ sequence_scheme)
```


```{r}
lapply(seq(1, 8, 1), 
       function(x){
         calculate_correlation(complete_sim_res, 
                               lt_df_with_blocks %>% filter(block_number == x)) %>% 
           mutate(block_number = x)
       }) %>% 
  bind_rows() %>% 
  ggplot(aes(x = block_number, y = pearson_cor, color = prior_info)) + 
  geom_point() + 
  geom_line() + 
  theme_classic()
```


```{r}

calculate_correlation <- function(complete_sim_res, lt_df_cleaned){
  
  temp_d <- complete_sim_res %>% 
      group_by(params_id, stimulus_idx, sim_id, sequence_scheme, complexity, prior_info) %>% 
      summarise(sample_n = mean(sample_n)) %>% 
      rename(trial_number = stimulus_idx) %>% 
      left_join(lt_df_cleaned, by = c("sequence_scheme", "complexity", "trial_number")) %>% 
      ungroup() 
  
  all_params_id <- temp_d %>% 
    distinct(params_id) %>% 
    pull()
  
  corr_value_df <- lapply(all_params_id, 
         function(x){
            sub_d <- temp_d %>% filter(params_id == x)
            pearson_cor <- cor(log(sub_d$sample_n), sub_d$log_mean_lt, use = "pairwise.complete.obs")
            return(tibble(
              pearson_cor = pearson_cor, 
              params_id = x
            ))
         }) %>% 
    bind_rows()
  
  corr_value_df <- temp_d %>% 
    select(params_id, prior_info) %>% 
    distinct(params_id, prior_info) %>% 
    left_join(corr_value_df, by = "params_id") %>% 
    arrange(-pearson_cor)
  
  return(corr_value_df)
    
}

calculate_correlation(complete_sim_res, lt_df_cleaned) %>% 
  ggplot(aes(x = prior_info, y = pearson_cor)) + 
  geom_point()

```


```{r}
complete_sim_res %>% 
  #filter(sequence_scheme == "BBBBBD") %>% 
  ggplot(aes(x = stimulus_idx, y = sample_n, color = complexity)) + 
  stat_summary(fun.data = "mean_cl_boot", geom = "pointrange",  position = position_dodge(width = .2)) +
  stat_summary(fun.data = "mean_cl_boot", geom = "line",  position = position_dodge(width = .2)) + 
  theme_classic()+
  langcog::scale_color_solarized(name = "Complexity") + 
  facet_grid(prior_info~sequence_scheme)
```








```{r}
sim_res %>% 
  group_by(sim_id, subject_id, stimulus_idx) %>% 
  summarise(sample_n = n()) %>% 
  filter(!is.na(stimulus_idx)) %>% 
  left_join(ss_type_df, by = "sim_id" ) %>% 
  ggplot(aes(x = stimulus_idx, y = sample_n, color = complexity)) + 
  stat_summary(fun.data = "mean_cl_boot", geom = "pointrange",  position = position_dodge(width = .2)) +
  stat_summary(fun.data = "mean_cl_boot", geom = "line",  position = position_dodge(width = .2)) + 
  theme_classic()+
  langcog::scale_color_solarized(name = "Complexity") + 
  facet_wrap(~sequence_scheme)
```

