---
title: "Fitting model to data"
author: "anjie"
date: "8/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(matrixStats)
library(partitions)

source(here("helper/make_scheme_and_params.R"))
source(here("helper/get_eig_faster.R"))
source(here("helper/get_stimuli.R"))
source(here("helper/get_observation.R"))
source(here("helper/main_simulation_helper.R"))
source(here("helper/params_helper_experiment.R"))

d <- read_csv(here("data/processed_rt_task_data.csv"))
```

Figuring out the sequence and generate the stimuli sequence with all the parameters 

```{r}
alpha_epsilon = c(1)
beta_epsilon = c(1)
alpha_priors = c(1)
beta_priors = c(1)
noise_parameters = c(0.05)
eigs_from_world = c(0.001)
max_observation = 500
fixed_length_complexity = FALSE 
feature_space_n = 7
simple_feature_n = 1
complex_feature_n = 3
dissimilar_ratio = 1
sequence_scheme = c("BDBBBB", "BBBDBB", "BBBBBD", "BBBBBB")
complexity = c("complex", "simple")
n <- 2

full_params_df <- make_simulation_params(n = n,
                                         sequence_scheme, 
                                         complexity, 
                                         alpha_priors, 
                                         beta_priors, 
                                         alpha_epsilon, 
                                         beta_epsilon, 
                                         noise_parameters, 
                                         eig_from_world, 
                                         max_observation, 
                                         fixed_length_complexity, 
                                         feature_space_n, 
                                         simple_feature_n, 
                                         complex_feature_n, 
                                         dissimilar_ratio) 

# note that this should happen in make_simulation_params
full_params_df <- full_params_df %>%
  left_join(expand_grid(sub_id = 1:n, params_id = 1, sim_id = 1:8))

```

Running the simulation. 

```{r}
all_sims_res <- full_params_df %>%
  group_by(params_id, sim_id, sub_id) %>%
  nest() %>%
  mutate(results = map(data, 
                       function(df) main_simulation(params_df = df, 
                                                    forced_exposure = FALSE,
                                                    forced_sample = NULL))) %>%
  unnest(cols = c(data, results))
```

Clean and visualize. 

```{r}
complete_sim_res <- all_sims_res %>% 
  group_by(params_id, sim_id, subject_id, stimulus_idx) %>% 
  summarise(sample_n = n()) %>% 
  filter(!is.na(stimulus_idx)) %>% 
  left_join(full_params_df %>% select(-n), by = c("params_id", "sim_id")) %>% 
  mutate(prior_info = paste("a", alpha_prior, "b", beta_prior, sep = "_")) %>% 
  mutate(eig_info = paste("np", noise_parameter, "ee", eig_from_world))

ggplot(complete_sim_res, 
       aes(x = stimulus_idx, y = sample_n)) + 
  geom_point() +
  geom_smooth() + 
  facet_wrap(~sequence_scheme)
```


