---
title: "params_experiment"
author: "anjie"
date: "8/9/2021"
output: html_document
---
```{r}
library(tidyverse)
 theme_set(theme_classic())
library(here)
library(matrixStats)
library(profvis)

source(here("helper/get_eig_faster.R"))
source(here("helper/get_stimuli.R"))
source(here("helper/get_observation.R"))
source(here("helper/main_simulation_under_construction.r"))
source(here("helper/params_helper_experiment.r"))

```


# Set up parameters here
```{r}
# DIY your own stimuli sequence 
feature_theta = 0.2
num_features_simple = 1
dissimilarity_ratio = 0.8

test_background <- generate_creature_sequence(
  block_length = 7, 
  deviant_positions = c(),  # takes a vector, 
  total_feature = 1, 
  feature_theta = feature_theta, 
  feature_number = num_features_simple, 
  dissimilar_ratio = dissimilarity_ratio)

subject_n <- 100
stimuli_sequence <- test_background # replace with whatever you want to try out
noise_parameter <- 0.001
eig_from_world <- 0.005
max_observation <- 500
grid_theta <- seq(0.1, 1, 0.2)
grid_epsilon <- seq(0.1, 1, 0.2)
alpha_epsilon = 1 
beta_epsilon = 1

alpha_prior <- c(1, 5, 10)
beta_prior <- c(1, 5, 10)
forced_sample = NULL



```

# Habituation 

```{r}

all_false_params <- expand_grid(
  subject_n,
  stimuli_sequence = nest(test_background),
  noise_parameter,
  eig_from_world, 
  max_observation,
  alpha_prior, 
  beta_prior, 
  forced_sample
) %>%
  mutate(
  type = "all_false"
  )

all_true_params <- expand_grid(
  subject_n,
  stimuli_sequence = nest(test_background %>% mutate(V1 = as.logical(1-V1))),
  noise_parameter,
  eig_from_world, 
  max_observation,
  alpha_prior, 
  beta_prior, 
  forced_sample
) %>%
  mutate(
  type = "all_true"
  )

symmetry_params <- bind_rows(all_false_params, 
                        all_true_params) %>% 
   mutate(sim_id = row_number())# crucial for linking

symmetry_res <- pmap_dfr(symmetry_params, 
     simulation_wrapper
     )

#saveRDS(sim_res, file = "sim_res.rds")
```

```{r}
symmetry_res %>% 
  left_join(symmetry_params %>% select(-type), by = "sim_id") %>% 
  mutate(
    prior_params = paste0("a", alpha_prior, "b", beta_prior), 
    prior_ratio = alpha_prior / beta_prior) %>% 
  ggplot(aes(x = t, y = EIG, color = type)) + 
  #geom_jitter(alpha = .1) + 
  stat_summary(fun.data = "mean_cl_boot", position = position_jitter(width = .3), alpha = .5) + 
  facet_wrap(~reorder(prior_params, prior_ratio)) 
```


```{r}
symmetry_res %>% 
  left_join(symmetry_params %>% select(-type), by = "sim_id") %>% 
  mutate(
    prior_params = paste0("a", alpha_prior, "b", beta_prior), 
    prior_ratio = alpha_prior / beta_prior) %>% 
  group_by(sim_id, prior_params, subject_id, stimulus_idx, prior_ratio,type
           ) %>% 
  mutate(sample_n = n()) %>% 
  ggplot(aes(x = stimulus_idx, y = sample_n, color = type)) + 
  #geom_jitter(alpha = .1) + 
  stat_summary(fun.data = "mean_cl_boot", position = position_jitter(width = .3), alpha = .5) + 
  facet_wrap(~reorder(prior_params, prior_ratio)) + 
  ylim(0, 20)+ 
  scale_x_continuous(breaks = seq(1, 8, 1)) 
```


## True vs False situation 
```{r}
test_background
```




# Dishabituation {.tabset}

## Early vs Late 
```{r}
early_d_sim_sequence <- generate_creature_sequence(
  block_length = 8, 
  deviant_positions = c(3),  # takes a vector, 
  total_feature = 1, 
  feature_theta = 0.99, 
  feature_number = num_features_simple, 
  dissimilar_ratio = dissimilarity_ratio)

early_d_sim_sequence$V1 <- c(TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE)

late_d_sim_sequence <- generate_creature_sequence(
  block_length = 8, 
  deviant_positions = c(6),  # takes a vector, 
  total_feature = 1, 
  feature_theta = 0.99, 
  feature_number = num_features_simple, 
  dissimilar_ratio = dissimilarity_ratio)
late_d_sim_sequence$V1 <- c(TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE)

early_params <- expand_grid(
  subject_n,
  stimuli_sequence = nest(early_d_sim_sequence),
  noise_parameter,
  eig_from_world, 
  max_observation,
  alpha_prior, 
  beta_prior, 
  forced_sample, 
  sequence_scheme = "BBDBBBBB"
) 

late_params <- expand_grid(
  subject_n, 
  stimuli_sequence = nest(late_d_sim_sequence),
  noise_parameter,
  eig_from_world, 
  max_observation,
  alpha_prior, 
  beta_prior, 
  forced_sample, 
  sequence_scheme = "BBBBBDBB"
) 

dishabituation_params <- bind_rows(early_params, late_params) %>% mutate(sim_id = row_number())
```


```{r}
dishab_res <- pmap_dfr(dishabituation_params %>% select(-sequence_scheme), 
     simulation_wrapper
     )
```

```{r}
saveRDS(dishab_res, "dishab_res.rds")
```

```{r}
dishab_res %>% 
  left_join(dishabituation_params, by = "sim_id") %>% 
  mutate(
    prior_params = paste0("a", alpha_prior, "b", beta_prior), 
    prior_ratio = alpha_prior / beta_prior) %>% 
  group_by(sim_id, sequence_scheme, prior_params, subject_id, stimulus_idx, prior_ratio
           ) %>% 
  mutate(sample_n = n()) %>% 
  ggplot(aes(x = stimulus_idx, y = sample_n, color = reorder(prior_params, prior_ratio))) + 
  #geom_jitter(alpha = .1) + 
  stat_summary(fun.data = "mean_cl_boot", position = position_jitter(width = .3), alpha = .5) + 
  facet_wrap(~sequence_scheme) + 
  ylim(0, 20)+ 
  scale_x_continuous(breaks = seq(1, 8, 1)) 
```
```{r}
dishab_res %>% 
  left_join(dishabituation_params, by = "sim_id") %>% 
  mutate(
    prior_params = paste0("a", alpha_prior, "b", beta_prior), 
    prior_ratio = alpha_prior / beta_prior) %>% 
  group_by(sim_id, sequence_scheme, prior_params, subject_id, stimulus_idx, prior_ratio
           ) %>% 
  mutate(sample_n = n()) %>% 
  ggplot(aes(x = stimulus_idx, y = sample_n)) + 
  #geom_jitter(alpha = .1) + 
  stat_summary(fun.data = "mean_cl_boot", alpha = .5) +
  facet_wrap(~sequence_scheme) + 
  ylim(0, 20)+ 
  scale_x_continuous(breaks = seq(1, 8, 1))  + 
  theme_classic()
```




## Multiple deviants - BBBDDDBB
```{r}
multi_d_sim_sequence <- generate_creature_sequence(
  block_length = 8, 
  deviant_positions = c(3),  # takes a vector, 
  total_feature = 1, 
  feature_theta = 0.99, 
  feature_number = num_features_simple, 
  dissimilar_ratio = dissimilarity_ratio)

multi_d_sim_sequence$V1 <- c(TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE)

multi_d_sim_params <- expand_grid(
  subject_n, 
  stimuli_sequence = nest(multi_d_sim_sequence),
  noise_parameter,
  eig_from_world, 
  max_observation,
  alpha_prior, 
  beta_prior, 
  forced_sample, 
  sequence_scheme = "BBBDDDBB"
) %>% mutate(sim_id = row_number())
```

```{r}
multi_d_res <- pmap_dfr(multi_d_sim_params %>% select(-sequence_scheme), 
     simulation_wrapper
     )
```

```{r}
saveRDS(multi_d_res, "multi_d_res.rds")
```

```{r}
multi_d_res %>% 
  left_join(multi_d_sim_params, by = "sim_id") %>% 
  mutate(
    prior_params = paste0("a", alpha_prior, "b", beta_prior), 
    prior_ratio = alpha_prior / beta_prior) %>% 
  group_by(sim_id, sequence_scheme, prior_params, subject_id, stimulus_idx, prior_ratio
           ) %>% 
  mutate(sample_n = n()) %>% 
  ggplot(aes(x = stimulus_idx, y = sample_n, color = reorder(prior_params, prior_ratio))) + 
  #geom_jitter(alpha = .1) + 
  stat_summary(fun.data = "mean_cl_boot", position = position_jitter(width = .3), alpha = .5) + 
  facet_wrap(~sequence_scheme) + 
  ylim(0, 20)+ 
  scale_x_continuous(breaks = seq(1, 8, 1)) 
```


```{r}
multi_d_res %>% 
  left_join(multi_d_sim_params, by = "sim_id") %>% 
  mutate(
    prior_params = paste0("a", alpha_prior, "b", beta_prior), 
    prior_ratio = alpha_prior / beta_prior) %>% 
  group_by(sim_id, sequence_scheme, prior_params, subject_id, stimulus_idx, prior_ratio
           ) %>% 
  mutate(sample_n = n()) %>% 
  ggplot(aes(x = stimulus_idx, y = sample_n)) + 
  #geom_jitter(alpha = .1) + 
  stat_summary(fun.data = "mean_cl_boot", alpha = .5) + 
  facet_wrap(~sequence_scheme) + 
  ylim(0, 20)+ 
  scale_x_continuous(breaks = seq(1, 8, 1)) + 
  theme_classic()
```


# Complexity effect 

```{r}
complexity_s_sequence<- generate_creature_sequence(
  block_length = 8, 
  deviant_positions = c(5),  # takes a vector, 
  total_feature = 12, 
  feature_theta = 0.99, 
  feature_number = num_features_simple, 
  dissimilar_ratio = 1)


complexity_c_sequence <- generate_creature_sequence(
  block_length = 8, 
  deviant_positions = c(5),  # takes a vector, 
  total_feature = 12, 
  feature_theta = 0.99, 
  feature_number = 5, 
  dissimilar_ratio = 1)

simple_stimuli <- expand_grid(
  subject_n,
  stimuli_sequence = nest(complexity_s_sequence),
  noise_parameter,
  eig_from_world, 
  max_observation,
  alpha_prior, 
  beta_prior, 
  forced_sample, 
  complexity = "simple"
) 

complex_stimuli <- expand_grid(
  subject_n, 
  stimuli_sequence = nest(complexity_c_sequence),
  noise_parameter,
  eig_from_world, 
  max_observation,
  alpha_prior, 
  beta_prior, 
  forced_sample, 
  complexity = "complex"
) 

complexity_params <- bind_rows(simple_stimuli, complex_stimuli) %>% 
  mutate(sim_id = row_number())
```

```{r}

complexity_params_res <- pmap_dfr(complexity_params %>% select(-complexity), 
     simulation_wrapper
     )
```

```{r}
saveRDS(complexity_params_res, "complexity_res.RDS")
```

```{r}
complexity_params_res %>% 
  left_join(complexity_params, by = "sim_id") %>% 
  mutate(
    prior_params = paste0("a", alpha_prior, "b", beta_prior), 
    prior_ratio = alpha_prior / beta_prior) %>% 
  group_by(sim_id, complexity,  prior_params, subject_id, stimulus_idx, prior_ratio
           ) %>% 
  mutate(sample_n = n()) %>% 
  ggplot(aes(x = stimulus_idx, y = sample_n, color = complexity, group = complexity)) + 
  #geom_jitter(alpha = .1) + 
  stat_summary(fun.data = "mean_cl_boot",  alpha = .5) + 
  #facet_wrap(~sequence_scheme) + 
  ylim(0, 20)+ 
  scale_x_continuous(breaks = seq(1, 8, 1)) #+ 
  #facet_wrap(~reorder(prior_params, prior_ratio))
```
no complexity effect when same feature space, but what about different feature space? 

```{r}
longv_sequence <- generate_creature_sequence(
  block_length = 8, 
  deviant_positions = c(5),  # takes a vector, 
  total_feature = 5, 
  feature_theta = 0.99, 
  feature_number = 1, 
  dissimilar_ratio = 1) %>% 
  mutate(V1 = TRUE, 
         V2 = TRUE, 
         V3 = TRUE, 
         V4 = TRUE, 
         V5 = TRUE) 

longv_sequence[5,1:5] <- 1-longv_sequence[3,1:5]

shortv_sequence <- longv_sequence %>% 
 select(-c(V2, V3, V4, V5))
  
shortv_sequence[5, 1] <- FALSE

simple_stimuli <- expand_grid(
  subject_n,
  stimuli_sequence = nest(shortv_sequence),
  noise_parameter,
  eig_from_world, 
  max_observation,
  alpha_prior, 
  beta_prior, 
  forced_sample, 
  complexity = "short_simple"
) 

complex_stimuli <- expand_grid(
  subject_n, 
  stimuli_sequence = nest(longv_sequence),
  noise_parameter,
  eig_from_world, 
  max_observation,
  alpha_prior, 
  beta_prior, 
  forced_sample, 
  complexity = "long_complex"
) 

length_complexity_params <- bind_rows(simple_stimuli, complex_stimuli) %>% 
  mutate(sim_id = row_number())
```

```{r}

length_complexity_params_res <- pmap_dfr(length_complexity_params %>% select(-complexity), 
     simulation_wrapper
     )
```
```{r}
saveRDS(length_complexity_params_res, "length_complexity_params_res.rds")

```

```{r}
length_complexity_params_res %>% 
  left_join(length_complexity_params %>% 
              mutate(prior_params = paste0("a", alpha_prior, "b", beta_prior), 
   prior_ratio = alpha_prior / beta_prior) %>% 
     select(sim_id, complexity, prior_params, prior_ratio), by = "sim_id") %>% 
 
  group_by(sim_id,  subject_id, stimulus_idx, prior_params
           ) %>% 
  mutate(sample_n = n()) %>% 
  ggplot(aes(x = stimulus_idx, y = sample_n, color = complexity)) + 
  #geom_jitter(alpha = .1) + 
  stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = .5), alpha = .5) +
  #ylim(0, 20)+ 
  scale_x_continuous(breaks = seq(1, 8, 1)) 
  #facet_wrap(~reorder(prior_params, prior_ratio))
```

# Familiarity preference 






















