---
title: "model_visualization"
author: "anjie"
date: "8/10/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(matrixStats)
library(here)
varying_prior_sim <- readRDS(here("m3_nfl_dependent_observation/varying_prior_sim.rds"))
noise_sim_res <- readRDS(here("m3_nfl_dependent_observation/noise_sim_res.rds"))
```


```{r}


source(here("helper/get_eig_faster.R"))
source(here("helper/get_stimuli.R"))
source(here("helper/get_observation.R"))
source(here("helper/main_simulation_under_construction.r"))

num_features = 1
num_features_simple = 1
num_feature_complex = 6
trials_per_block = 6
deviant_positions = c()
feature_theta = 0.9
dissimilarity_ratio = 0.2
noise_parameter = 0.001

## grid approximation related 
grid_theta <- seq(0.1, 1, 0.2)
grid_epsilon <- seq(0.1, 1, 0.2)
alpha_prior = 1
beta_prior = 1
alpha_epsilon = 10 
beta_epsilon = 1

## eig related 
env_eig = 0.008
max_obs = 500

## experiment related 
subject_n = 10

second_background <- generate_creature_sequence(
  block_length = 2, 
  deviant_positions = deviant_positions,  # takes a vector, 
  total_feature = num_features, 
  feature_theta = feature_theta, 
  feature_number = num_features_simple, 
  dissimilar_ratio = dissimilarity_ratio)

second_deviant <- second_background
second_deviant$V1[2] <- FALSE
```

```{r}
b_sim <- main_simulations(subject_n = 500,
                second_background, 
                noise_parameter = noise_parameter, 
                eig_from_world = env_eig,
                max_observation = max_obs, # should this be per trial or in total? currently per trial 
                grid_theta = grid_theta, 
                grid_epsilon = grid_epsilon, 
                alpha_prior = 1, 
                beta_prior = 12,
                alpha_epsilon = alpha_epsilon, 
                beta_epsilon = beta_epsilon, 
                forced_exposure = FALSE,
                forced_sample = NULL) %>% 
  mutate(type = "b")

d_sim <- main_simulations(subject_n = 500,
                second_deviant, 
                noise_parameter = noise_parameter, 
                eig_from_world = env_eig,
                max_observation = max_obs, # should this be per trial or in total? currently per trial 
                grid_theta = grid_theta, 
                grid_epsilon = grid_epsilon, 
                alpha_prior = 1, 
                beta_prior = 12,
                alpha_epsilon = alpha_epsilon, 
                beta_epsilon = beta_epsilon, 
                forced_exposure = FALSE,
                forced_sample = NULL) %>% 
  mutate(type = "d")
```



```{r}
bind_rows(b_sim, d_sim) %>% 
  filter(stimulus_idx == 2) %>% 
  #group_by(stimulus_idx, subject_id, type) %>% 
  #summarise(sum_eig = sum(EIG)) %>% 
  ggplot(aes(x = EIG, fill = type)) + 
  geom_density(alpha = .3)
```
```{r}
noise_sim_res
```


```{r}
get_fam_pref_df(noise_sim_res) %>% 
  pivot_longer(cols = c("bckgd_mean_lt", "deviant_mean_lt"), 
               names_to = "type",
               values_to = "mean_lt") %>% 
  select(sim_id, forced_exposure_n, noise_parameter, eig_from_world, type, mean_lt) %>% 
  
  
```


```{r}
b_df <- noise_sim_res %>% 
  select(sim_id, type, mean_lt, sd_lt, n) %>% 
  filter(type == "background") %>% 
  pivot_wider(names_from = type, 
              values_from = "mean_lt") %>% 
  rename(bckgd_mean_lt = background, bckgd_sd_lt = sd_lt)

d_df <- noise_sim_res %>% 
   select(sim_id, type, mean_lt, sd_lt, n) %>% 
  filter(type == "deviant") %>% 
  pivot_wider(names_from = type, 
              values_from = "mean_lt") %>% 
  rename(deviant_mean_lt = deviant, deviant_sd_lt = sd_lt) %>% 
  unnest() %>% 
  select(-c(sim_id,  n))

bind_cols(b_df, d_df) %>% 
  select(sim_id, bckgd_mean_lt, deviant_mean_lt, bckgd_sd_lt, deviant_sd_lt, n) %>% 
  pmap_df(., t_test_wrapper) %>% 
  ggplot(aes(x = `p-value`)) + 
  geom_histogram()
```

```{r}
noise_sim_res
```
```{r}
noise_sim_res
```


```{r}
get_fam_pref_df(noise_sim_res) %>% 
  select(sim_id, bckgd_mean_lt, deviant_mean_lt, bckgd_sd_lt, deviant_sd_lt, n) %>% 
  pmap_df(., t_test_wrapper) %>% 
  ggplot(aes(x = `p-value`)) + 
  geom_histogram()
```

