
```{r}
library(tidyverse)
library(here)
library(ggthemes)
library(reticulate)

#d <- read_csv(here("data/param_fit_raw/kl.csv"))
nl_d <- read_csv(here("data/param_fit_raw/no_learning.csv"))
nn_d <- read_csv(here("nn_try.csv"), col_names = FALSE)
colnames_d <- read_csv(here("colnames.csv"))
colnames(nn_d) <-c(colnames(colnames_d)[-1], "file_id")


#test_d <- read_csv(here("data/test_d.csv"))

source(here("helper/fitting.r"))
source(here("helper/scaling.r"))
```


```{r}
nn_d
```


```{r}
summarized_nn_d <- nn_d %>% 
  filter(EIG != 999) %>% 
  group_by(file_id, j_i, b_val, d_val,stimulus_id,  mu_prior, v_prior, alpha_prior, beta_prior, weig, stim_squence, forced_exposure_max, violation_type) %>% 
  count() %>% 
  rename(n_samples = n ) %>% 
  rename(trial_num = stimulus_id) %>% 
  rename(sub_id = file_id) %>% 
  rename(batch_id = j_i) %>% 
  mutate(
    test_type = case_when(
      grepl("D", stim_squence) ~ "nov", 
      !grepl("D", stim_squence) ~ "fam"
    ),
    fam_trial = str_length(stim_squence) - 1 
  ) %>% 
  mutate(
    param_info = paste("v", v_prior, "ap", alpha_prior, "bp", beta_prior, "weig", weig, sep = "_"), 
    ab_prior = paste("a", alpha_prior, "b", beta_prior, sep = "_")
  ) %>% 
  mutate(dist = abs(b_val - d_val)) %>% 
  group_by(sub_id, batch_id, trial_num, stim_squence, test_type, fam_trial, param_info) %>% 
  summarise(
    mean_sample = mean(n_samples)
  ) 
```

```{r}
# distribution of the error out trial

error_distribution_d <- nn_d %>% 
  filter(!is.na(EIG)) %>% 
  rename(trial_num = stimulus_id) %>% 
  rename(sub_id = file_id) %>% 
  rename(batch_id = j_i) %>% 
  mutate(
    param_info = paste("v", v_prior, "ap", alpha_prior, "bp", beta_prior, "weig", weig, sep = "_"), 
  ) %>% 
  ungroup() %>% 
  mutate(
    error = if_else(EIG == 999, TRUE, FALSE)
  ) %>% 
  ungroup() %>% 
  group_by(error, param_info) %>% 
  count()
  
```


```{r}
error_distribution_d %>% 
  filter(error == FALSE) %>% 
  rename(success_n = n) %>% 
  select(-error) %>% 
  left_join(error_distribution_d %>% filter(error == TRUE) %>% rename(error_n = n) %>% select(-error), by = "param_info") %>% 
  select(param_info, error_n, success_n) %>% 
  ungroup() %>% 
  mutate(error_n = ifelse(is.na(error_n), 0, error_n)) %>% 
  mutate(rate = error_n / (error_n + success_n)) %>% 
  ggplot(aes(x = param_info, y = rate)) + 
  geom_point() +  
  coord_flip() + 
  theme_few() +
  ylab("Error Rate")
```


```{r}
nl_d

colnames()



clean_nn_d <- nn_d %>% 
  tail(-2)

colnames(clean_nn_d) <- c("..1","sub_id","batch_id", "trial_num","stim_sequence",
                          "violation","b_val","d_val","v_prior","alpha_prior","beta_prior",      
                          "forced_exposure_num","weig","n_samples")

clean_nn_d
```

```{r}
clean_nn_d
```



```{r}
d %>% 
  ggplot(aes(x = n_samples)) + 
  geom_density()
```

```{r}
d 

summarised_d <- d %>% 
  mutate(
    param_info = paste("v", v_prior, "ap", alpha_prior, "bp", beta_prior, "weig", weig, sep = "_"), 
    ab_prior = paste("a", alpha_prior, "b", beta_prior, sep = "_")
  ) %>% 
  mutate(dist = abs(b_val - d_val)) %>% 
  group_by(sub_id, batch_id, trial_num, stim_sequence, test_type, param_info) %>% 
  summarise(
    mean_sample = mean(n_samples)
  )
  

```


```{r}
nov_sim <- summarised_d %>% 
  ungroup() %>% 
  filter(grepl("D", stim_sequence)) %>% 
  select(-stim_sequence) %>% 
  group_by(batch_id, trial_num, dist) %>% 
  summarise(nov_sample = mean(mean_sample))%>% 
  ungroup()

fam_sim  <- summarised_d %>% 
  ungroup() %>% 
  filter(!grepl("D", stim_sequence)) %>% 
  select(-stim_sequence) %>% 
  filter(trial_num != 0) %>% 
  group_by(batch_id, trial_num, dist) %>% 
  summarise(fam_sample = mean(mean_sample)) %>% 
  ungroup()


nov_sim %>% 
  left_join(fam_sim %>% select(batch_id, trial_num, fam_sample) , 
            by = c("batch_id", "trial_num")) %>% 
  mutate(dishab_magnitude = nov_sample - fam_sample) %>% 
  ggplot(aes(x = dist,  y = dishab_magnitude)) + 
  #stat_summary(fun.data = "mean_cl_boot") +
  geom_point(alpha = .3) + 
  facet_wrap(~trial_num) + 
  theme_few() + 
  geom_smooth(method = "lm")
  
```


# check out the general trend 

```{r}
summarised_d %>% ungroup() %>% distinct(param_info)
```


```{r}
summarized_nn_d %>% 
  filter(trial_num == str_length(stim_squence) - 1) %>% 
  ggplot(aes(x = trial_num, y = mean_sample, color = test_type)) + 
  stat_summary(fun.data = "mean_cl_boot") +
  theme_few()  + 
  facet_wrap(~param_info, scales = "free")
```


```{r}
summarised_d %>% 
  ggplot(aes(x = trial_num, y = mean_sample, color = test_type)) + 
  stat_summary(fun.data = "mean_cl_boot") +
  theme_few() + 
  facet_wrap(~param_info)
```





# Wrangle d into what we actually want 

```{r}


tidy_d <-d %>% 
  rename(sub_id = file_id, 
         batch_id = j_i, 
         stimuli_sequence = stim_squence) %>% 
  mutate(trial_number = stimulus_id + 1) %>% 
  select(batch_id, sub_id, trial_number, stimuli_sequence, complexity_type, n) %>% 
  mutate(param_info = "selected")


summarised_sample <- tidy_d %>% 
  group_by(param_info, stimuli_sequence, trial_number, complexity_type) %>% 
  rename(complexity = complexity_type) %>% 
  summarise(mean_sample = mean(n)) 


summary_test_d <- test_d %>% 
  group_by(stimuli_sequence, trial_number, trial_type, complexity) %>% 
  summarise(mean_lt = mean(trial_looking_time))
```


```{r}
all_sim_d <- summary_test_d %>% 
  left_join(summarised_sample, by = c("stimuli_sequence", "trial_number", "complexity")) %>% 
  ungroup() %>% 
  group_by(param_info) %>% 
  nest(data = -param_info)

scaling_param_f <- get_scaling_param_flipped(all_sim_d)
fitting_test_res <- get_fitting_stats(all_sim_d )

fitting_test_res
```
```{r}
prev_complexity <- readRDS(here("prev_cache/test_by_complexity_fit.RDS"))
prev_complexity %>% filter(param_info == "mu_0_v_1_a_1_b_1_ep_1e-04")
```

# make plot 

```{r} 
scaled_tidy_n <- tidy_d %>% 
  mutate(
    scaled_sample_n = n * scaling_param_f$coef + scaling_param_f$intercept
  ) %>% mutate(type = "sim") %>% 
  select(trial_number, stimuli_sequence, scaled_sample_n, type)

test_d %>% rename(scaled_sample_n = trial_looking_time) %>% 
  ungroup() %>% 
   select(trial_number, stimuli_sequence, scaled_sample_n) %>% 
  mutate(type = "behavior") %>% 
  bind_rows(scaled_tidy_n) %>% 
 ggplot(aes(x = trial_number, y = scaled_sample_n, color = type)) + 
  stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = .2)) + 

  facet_wrap(~stimuli_sequence) + 
  theme_few()
```

